### ISSUE TITLE
NuGet Package cannot be restored

### ISSUE THREAD

**Issue by martinsmuts** [codemillmatt/xamarin-u-aadb2c#1]
Hi,

I am having an issue with restoring the Microsoft.Identity.Client (MSAL) package in VS. I get the following error: 
"Some Nuget Packages are missing from this solution. Click Restore from your online package sources."

When I perform the restore, I receive the following error: 
"Unable to find version '1.1.1-alpha0417 of package 'Microsoft.identity.Client'."

I have tried uninstalling and reinstalling the package in VS, but it won't allow me to perform the actual uninstall. 

Any ideas to solve this issue?

Sincerely,
Martin

**Comment by codemillmatt** [comment]
Thanks for pointing that out!

Lol ... they removed that version of the package from NuGet & updated it. I updated the solution to the latest version & just tested it on iOS - seems to work fine.

BTW - I added a compiler directive to throw an exception immediately upon build time until the tenant, application ID, policies, etc are entered.
