### ISSUE TITLE
Can i use this sample in same manner with Azure Mobile App

### ISSUE THREAD

**Issue by chrisgate** [codemillmatt/xamarin-u-aadb2c#2]
@codemillmatt   If I can not use this sample in same manner with Azure Mobile App do you have any sample you can point me too.

Thanks

**Comment by chrisgate** [comment]
@codemillmatt tho the sdk in alpha freezed my VS till i downgrade it to preview and i also created Function App as showed in the video but can u help me with what should be in here bcoz my app refused to run with error (An error occur while logging in)
 
 public class B2CConstants
    {
//        #error Setup the tenant and grab the various ID - scopes - and policy names
            
        public static readonly string Tenant = "I KNOW THIS";
        public static readonly string ClientId = "I KNOW THIS";
        public static readonly string MSALRedirectUri = "msalI KNOW THIS//auth";

        public static readonly string SignInUpPolicy = "B2C_1_B2C_SignUpIn";
        public static readonly string PasswordResetPolicy = "";
        public static readonly string EditProfilePolicy = "";

        public static readonly string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/";
        public static readonly string SignUpInAuthority = $"{AuthorityBase}{SignInUpPolicy}";
        public static readonly string PasswordResetAuthority = $"{AuthorityBase}{PasswordResetPolicy}";
        public static readonly string EditProfileAuthority = $"{AuthorityBase}{EditProfilePolicy}";

        public static string[] Scopes = new string[] {I DONT GET THIS};
        
        public static string BestSongsUrl = "I DONT GET THIS";
        internal static IEnumerable<string> ApplicationScopes = "I DONT GET THIS";
    }

And my function URL where am i going to use it?


Thanks

**Comment by codemillmatt** [comment]
I'm going to be putting together a sample for Azure Mobile Apps soon (week of 26-March).

The MSAL library is blowing up on you?

**Comment by codemillmatt** [comment]
Also - I'm assuming for the `I DON'T GET THIS` portions - you mean in relation to Azure Mobile Apps?

**Comment by chrisgate** [comment]
@codemillmatt you a genius.........I DONT GET THIS........ meaning in relation to Azure Mobile Apps

Thanks

**Comment by codemillmatt** [comment]
Putting this link here for future reference: https://codemilltech.com/b2c-zumo/
